// phrases_fr.js
// "ENGLISH" : "FRENCH",

var phrasesFR = ('french',
    {
      'Generate':'Generate',
      'Mnemonic':'Mnemonic',
      'Derived Addresses':'Derived Addresses',
      'Derivation Path':'Derivation Path',
      'Mnemonic Code Converter':'Convertisseur de code mnémonique',
      'You can enter an existing BIP39 mnemonic, or generate a new random one. Typing your own twelve words will probably not work how you expect, since the words require a particular structure (the last word is a checksum).': 'Vous pouvez entrer une mnémonique BIP39 existante ou générer une nouvelle version aléatoire. Tapez vos propres douze mots ne fonctionnera probablement pas comme vous l\'attendez, car les mots nécessitent une structure particulière (le dernier mot est une somme de contrôle).',
      'Generate a random mnemonic, or enter your own below': 'Generate a random mnemonic, or enter your own below',
      'words': 'words',
      'Warning': 'Warning',
      'Entropy is an advanced feature. Your mnemonic may be insecure if this feature is used incorrectly.': 'Entropy is an advanced feature. Your mnemonic may be insecure if this feature is used incorrectly.',
      'Read more': 'Read more',
      'Entropy': 'Entropy',
      'Time To Crack': 'Time To Crack',
      'Event Count': 'Event Count',
      'Entropy Type': 'Entropy Type',
      'Bits Per Event': 'Bits Per Event',
      'Raw Entropy Words': 'Raw Entropy Words',
      'Total Bits': 'Total Bits',
      'Filtered Entropy': 'Filtered Entropy',
      'Raw Binary': 'Raw Binary',
      'Mnemonic Length': 'Mnemonic Length',
      'Use Raw Entropy (3 words per 32 bits)': 'Use Raw Entropy (3 words per 32 bits)',
      'Valid entropy values include:': 'Valid entropy values include:',
      'Binary': 'Binary',
      'Base 6': 'Base 6',
      'Dice': 'Dice',
      'Base 10': 'Base 10',
      'Hex': 'Hex',
      'Card': 'Card',
      'Supply my own source of entropy': 'Supply my own source of entropy',
      'Mnemonic Language': 'Mnemonic Language',
      'BIP39 Mnemonic': 'BIP39 Mnemonic',
      'BIP39 Passphrase (optional)': 'BIP39 Passphrase (optional)',
      'BIP39 Seed': 'BIP39 Seed',
      'Coin': 'Coin',
      'BIP32 Root Key': 'BIP32 Root Key',
      'Prefixes': 'Prefixes',
      'Purpose': 'Purpose',
      'Account': 'Account',
      'External / Internal': 'External / Internal',
      'The account extended keys can be used for importing to most BIP44 compatible wallets, such as mycelium or electrum.': 'The account extended keys can be used for importing to most BIP44 compatible wallets, such as mycelium or electrum.',
      'For more info see the BIP32 spec': 'For more info see the BIP32 spec',
      'Client': 'Client',
      'BIP32 Derivation Path': 'BIP32 Derivation Path',
      'Use hardened addresses': 'Use hardened addresses',
      'Use SegWit addresses (ie P2WPKH Nested In P2SH)': 'Use SegWit addresses (ie P2WPKH Nested In P2SH)',
      'Bitcoin Core': 'Bitcoin Core',
      'Multibit': 'Multibit',
      'For more info see': 'For more info see',
      'Block Explorers': 'Block Explorers',
      'Can be used with': 'Can be used with',
      'BIP49 is unavailable for this coin.': 'BIP49 is unavailable for this coin.',
      'The account extended keys can be used for importing to most BIP49 compatible wallets.': 'The account extended keys can be used for importing to most BIP49 compatible wallets.',
      'Account Extended Private Key': 'Account Extended Private Key',
      'Account Extended Public Key': 'Account Extended Public Key',
      'The BIP32 derivation path and extended keys are the basis for the derived addresses.': 'The BIP32 derivation path and extended keys are the basis for the derived addresses.',
      'BIP32 Extended Private Key': 'BIP32 Extended Private Key',
      'BIP32 Extended Public Key': 'BIP32 Extended Public Key',
      'Note these addreses are derived from the BIP32 Extended Key': 'Note these addreses are derived from the BIP32 Extended Key',
      'Path': 'Path',
      'Toggle': 'Toggle',
      'Address': 'Address',
      'Public Key': 'Public Key',
      'Private Key': 'Private Key',
      'Show more rows': 'Show more rows',
      'Show': 'Show',
      'More info': 'More info',
      'Mnemonic code for generating deterministic keys': 'Mnemonic code for generating deterministic keys',
      'Hierarchical Deterministic Wallets': 'Hierarchical Deterministic Wallets',
      'Multi-Account Hierarchy for Deterministic Wallets': 'Multi-Account Hierarchy for Deterministic Wallets',
      'Private Keys': 'Private Keys',
      'Be careful - it can be easy to make mistakes if you don t know what youare doing.': 'Be careful - it can be easy to make mistakes if you don t know what youare doing.',
      'This means flipping a fair coin, rolling a fair dice, noise measurements etc.': 'This means flipping a fair coin, rolling a fair dice, noise measurements etc.',
      'Do not store entropy.': 'Do not store entropy.',
      'Storing entropy (such as keeping a deck of cards in a specific shuffled order) is unreliable compared to storing a mnemonic.': 'Storing entropy (such as keeping a deck of cards in a specific shuffled order) is unreliable compared to storing a mnemonic.',
      'Instead of storing entropy, store the mnemonic generated from the entropy.': 'Instead of storing entropy, store the mnemonic generated from the entropy.',
      'The built in random generator can generally be trusted more than your own intuition about randomness.': 'The built in random generator can generally be trusted more than your own intuition about randomness.',
      'If cryptographic randomness isn t available in your browser, this page will show a warning and the generate button will not work.': 'If cryptographic randomness isn t available in your browser, this page will show a warning and the generate button will not work.',
      'In that case you might choose to use your own source of entropy.': 'In that case you might choose to use your own source of entropy.',
      'You are not a good source of entropy.': 'You are not a good source of entropy.',
      'License': 'License',
      'The software is provided \'as is\', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.': 'The software is provided \'as is\', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.',
      'Offline Usage': 'Offline Usage',
      'You can use this tool without having to be online.': 'You can use this tool without having to be online.',
      'In your browser, select file save-as, and save this page as a file.': 'In your browser, select file save-as, and save this page as a file.',
      'Double-click that file to open it in a browser on any offline computer.': 'Double-click that file to open it in a browser on any offline computer.',
      'Alternatively, download the file from the repository': 'Alternatively, download the file from the repository',
      'This project is 100% open-source code': 'This project is 100% open-source code',
      'Get the source code from the repository': 'Get the source code from the repository',
      'Libraries': 'Libraries',
      'Click field to hide QR': 'Click field to hide QR',
      'Click field to show QR': 'Click field to show QR',
      'Caution: Scanner may keep history': 'Caution: Scanner may keep history',
      '<code>m/44\'/0\'/0\'/0</code> generates public addresses': '<code>m/44\'/0\'/0\'/0</code> generates public addresses',
      '<code>m/44\'/0\'/0\'/1</code> generates change addresses': '<code>m/44\'/0\'/0\'/1</code> generates change addresses',
      '<code>m/44\'/0\'/0\'</code> generates extended keys for import / export': '<code>m/44\'/0\'/0\'</code> generates extended keys for import / export',
      '<code>m/44\'/0\'/1\'</code> for the next account. Continue incrementing for more accounts (most use a single account).': '<code>m/44\'/0\'/1\'</code> for the next account. Continue incrementing for more accounts (most use a single account).',
      'Accepts binary, base 6, 6-sided dice, base 10, hexadecimal, cards': 'Accepts binary, base 6, 6-sided dice, base 10, hexadecimal, cards',
      'BIP32 Extended Key': 'BIP32 Extended Key',
      'BIP32 Extended Key (addresses only)': 'BIP32 Extended Key (addresses only)',
      'Be careful - it can be easy to make mistakes if you don\'t know what you\'re doing.': 'Be careful - it can be easy to make mistakes if you don\'t know what you\'re doing.',
      'Do <strong>NOT</strong> use phrases from books, lyrics from songs, your birthday or steet address, keyboard mashing, or anything you <i>think</i> is random, because chances are overwhelming it isn\'t random enough for the needs of this tool.': 'Do <strong>NOT</strong> use phrases from books, lyrics from songs, your birthday or steet address, keyboard mashing, or anything you <i>think</i> is random, because chances are overwhelming it isn\'t random enough for the needs of this tool.',
      'Entropy values must be sourced from a <a href="https://en.wikipedia.org/wiki/Random_number_generation" target="_blank">strong source of randomness</a>.': 'Entropy values must be sourced from a <a href="https://en.wikipedia.org/wiki/Random_number_generation" target="_blank">strong source of randomness</a>.',
      'For more info see the <a href="http://www.mycelium.com/" target="_blank">Mycelium Wallet homepage</a>': 'For more info see the <a href="http://www.mycelium.com/" target="_blank">Mycelium Wallet homepage</a>',
      'For more info see the <a href="https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki" target="_blank">BIP39 spec</a>.': 'For more info see the <a href="https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki" target="_blank">BIP39 spec</a>.',
      'For more info see the <a href="https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki" target="_blank">BIP44 spec</a>.': 'For more info see the <a href="https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki" target="_blank">BIP44 spec</a>.',
      'For more info see the <a href="https://github.com/bitcoin/bitcoin/pull/8035" target="_blank">Bitcoin Core BIP32 implementation</a>': 'For more info see the <a href="https://github.com/bitcoin/bitcoin/pull/8035" target="_blank">Bitcoin Core BIP32 implementation</a>',
      'From entropy length (3 words per 32 bits)': 'From entropy length (3 words per 32 bits)',
      'If cryptographic randomness isn\'t available in your browser, this page will show a warning and the generate button will not work.': 'If cryptographic randomness isn\'t available in your browser, this page will show a warning and the generate button will not work.',
      'Mycelium Wallet': 'Mycelium Wallet',
      'Only enter the <code>xpub</code> extended key into block explorer search fields, never the <code>xprv</code> key.': 'Only enter the <code>xpub</code> extended key into block explorer search fields, never the <code>xprv</code> key.',
      'Read more at the <a href="https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki" target="_blank">official BIP32 spec</a>': 'Read more at the <a href="https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki" target="_blank">official BIP32 spec</a>',
      'Read more at the <a href="https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki">official BIP39 spec</a>': 'Read more at the <a href="https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki">official BIP39 spec</a>',
      'Read more at the <a href="https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki" target="_blank">official BIP44 spec</a>': 'Read more at the <a href="https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki" target="_blank">official BIP44 spec</a>',
      'See the demo at <a href="http://bip32.org/" target="_blank">bip32.org</a>': 'See the demo at <a href="http://bip32.org/" target="_blank">bip32.org</a>',

      'Strength': 'Strength',
      'The random mnemonic generator on this page uses a <a href="https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues" target="_blank">cryptographically secure random number generator</a>.': 'The random mnemonic generator on this page uses a <a href="https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues" target="_blank">cryptographically secure random number generator</a>.',
      'Use path <code>m/0\'/0\'</code> with hardened addresses.': 'Use path <code>m/0\'/0\'</code> with hardened addresses.',
      'Use path <code>m/44\'/0\'/0\'</code>.': 'Use path <code>m/44\'/0\'/0\'</code>.',
      'Use private keys at <a href="https://web.archive.org/web/20150707020924/https://brainwallet.org/" target="_blank">brainwallet.org</a>.': 'Use private keys at <a href="https://web.archive.org/web/20150707020924/https://brainwallet.org/" target="_blank">brainwallet.org</a>.',
      'Word Count': 'Word Count',

      'Based on estimates from zxcvbn using Filtered Entropy': 'Based on estimates from zxcvbn using Filtered Entropy',
      'Total bits of entropy may be less than indicated if any entropy event uses a weak source.': 'Total bits of entropy may be less than indicated if any entropy event uses a weak source.',
      'Be careful - it can be easy to make mistakes if you don\'t know what you are doing.': 'Be careful - it can be easy to make mistakes if you don\'t know what you are doing.',
      'Use path <code>m/0\'/0</code>.': 'Use path <code>m/0\'/0</code>.',
      'For more info see the <a href="https:\/\/github.com\/bitcoin\/bips\/blob\/master\/bip-0049.mediawiki" target="_blank">BIP49 spec<\/a>.': 'For more info see the <a href="https:\/\/github.com\/bitcoin\/bips\/blob\/master\/bip-0049.mediawiki" target="_blank">BIP49 spec<\/a>.',
      '<a href="https:\/\/en.wikipedia.org\/wiki\/Steganography#Physical" target="_blank">Steganography<\/a> may be beneficial when storing the mnemonic.': '<a href="https:\/\/en.wikipedia.org\/wiki\/Steganography#Physical" target="_blank">Steganography<\/a> may be beneficial when storing the mnemonic.',
      'Please refer to <a href="https:\/\/github.com\/iancoleman\/bip39\/blob\/master\/LICENSE" target="_blank">the software license<\/a> for more detail.': 'Please refer to <a href="https:\/\/github.com\/iancoleman\/bip39\/blob\/master\/LICENSE" target="_blank">the software license<\/a> for more detail.'
    }
);
