// phrases_es.js
// "ENGLISH" : "SPANISH",
var phrasesES = ("spanish",
    {
      'Generate':'Generar',
      'Mnemonic':'Mnemónico',
      'Derived Addresses':'Direcciones derivadas',
      'Derivation Path':'Ruta de derivación',
      'Mnemonic Code Converter':'Convertidor de código mnemónico',
      "You can enter an existing BIP39 mnemonic, or generate a new random one. Typing your own twelve words will probably not work how you expect, since the words require a particular structure (the last word is a checksum)." : "Puede ingresar un mnemotécnico BIP39 existente, o generar un nuevo aleatorio. Escribir sus propias doce palabras no funcionará probablemente como usted espera, puesto que las palabras requieren una estructura particular (la última palabra es una suma de comprobación).",
      "Generate a random mnemonic, or enter your own below" : "Genera un mnemónico aleatorio, o introduce tu propio abajo",
      "words" : "palabras",
      "Warning" : "Advertencia",
      "Entropy is an advanced feature. Your mnemonic may be insecure if this feature is used incorrectly." : "La entropía es una característica avanzada. Su mnemotécnico puede ser inseguro si esta función se utiliza incorrectamente.",
      "Read more" : "Lee mas",
      "Entropy" : "Entropía",
      "Time To Crack" : "Tiempo de crackear",
      "Event Count" : "Cuenta de eventos",
      "Entropy Type" : "Tipo de entropía",
      "Bits Per Event" : "Bits por evento",
      "Raw Entropy Words" : "Palabras de entropía cruda",
      "Total Bits" : "Total Bits",
      "Filtered Entropy" : "Entropía filtrada",
      "Raw Binary" : "Binario bruto",
      "Mnemonic Length" : "Longitud mnemónica",
      "Use Raw Entropy (3 words per 32 bits)" : "Utilice entropía cruda (3 palabras por 32 bits)",
      "Valid entropy values include:" : "Los valores de entropía válidos incluyen:",
      "Binary" : "Binario",
      "Base 6" : "Base 6",
      "Dice" : "Dado",
      "Base 10" : "Base 10",
      "Hex" : "Hex",
      "Card" : "Cartas",
      "Supply my own source of entropy" : "Suministrar mi propia fuente de entropía",
      "Mnemonic Language" : "Lenguaje Mnemotécnico",
      "BIP39 Mnemonic" : "BIP39 Mnemotécnico",
      "BIP39 Passphrase (optional)" : "BIP39 Frase de contraseña (opcional)",
      "BIP39 Seed" : "BIP39 Semilla",
      "Coin" : "Monedar",
      "BIP32 Root Key" : "BIP32 Clave de raíz",
      "Prefixes" : "Prefijos",
      "Purpose" : "Propósito",
      "Account" : "Cuenta",
      "External / Internal" : "External / Internal",
      "The account extended keys can be used for importing to most BIP44 compatible wallets, such as mycelium or electrum." : "Las claves extendidas de la cuenta se pueden utilizar para importar a la mayoría de las carteras compatibles con BIP44, como micelio o electrum.",
      "For more info see the BIP32 spec" : "Para más información ver la especificación BIP32",
      "Client" : "Cliente",
      "BIP32 Derivation Path" : "BIP32 Ruta de derivación",
      "Use hardened addresses" : "Usar direcciones endurecidas",
      "Use SegWit addresses (ie P2WPKH Nested In P2SH)" : "Utilizar direcciones SegWit (es decir, P2WPKH anidado en P2SH)",
      "Bitcoin Core" : "Bitcoin Core",
      "Multibit" : "Multibit",
      "For more info see" : "Para más información, consulte",
      "Block Explorers" : "Exploradores de bloques",
      "Can be used with" : "Se puede utilizar con",
      "BIP49 is unavailable for this coin." : "BIP49 no está disponible para esta moneda.",
      "The account extended keys can be used for importing to most BIP49 compatible wallets." : "Las claves extendidas de la cuenta se pueden utilizar para importar a la mayoría de las carpetas compatibles BIP49.",
      "Account Extended Private Key" : "Clave privada extendida de la cuenta",
      "Account Extended Public Key" : "Clave pública extendida de cuenta",
      "The BIP32 derivation path and extended keys are the basis for the derived addresses." : "La ruta de derivación BIP32 y las claves extendidas son la base para las direcciones derivadas.",
      "BIP32 Extended Private Key" : "Clave privada extendida BIP32",
      "BIP32 Extended Public Key" : "Clave pública extendida BIP32",
      "Note these addreses are derived from the BIP32 Extended Key" : "Tenga en cuenta que estos addreses se derivan de la BIP32 Clave extendida",
      "Path" : "Sendero",
      "Toggle" : "Palanca",
      "Address" : "Número de cuenta",
      "Public Key" : "Llave pública",
      "Private Key" : "Llave privada",
      "Show more rows" : "Mostrar más filas",
      "Show" : "Mas",
      "More info" : "Más información",
      "Mnemonic code for generating deterministic keys" : "Código mnemotécnico para generar claves deterministas",
      "Hierarchical Deterministic Wallets" : "Jerárquico Determinista billetera",
      "Multi-Account Hierarchy for Deterministic Wallets" : "Jerarquía de varias cuentas para Determinista billetera",
      "Private Keys" : "Claves privadas",
      "Be careful - it can be easy to make mistakes if you don t know what youare doing." : "Tenga cuidado - puede ser fácil cometer errores si no sabe lo que está haciendo.",
      "This means flipping a fair coin, rolling a fair dice, noise measurements etc." : "Esto significa lanzar una moneda justa, rodar unos dados justos, medidas de ruido, etc.",
      "Do not store entropy." : "No almacene la entropía.",
      "Storing entropy (such as keeping a deck of cards in a specific shuffled order) is unreliable compared to storing a mnemonic." : "Almacenar entropía (como mantener una baraja de cartas en un orden barajado específico) no es confiable en comparación con el almacenamiento de un mnemotécnico.",
      "Instead of storing entropy, store the mnemonic generated from the entropy." : "En lugar de almacenar entropía, almacenar el mnemónico generado de la entropía.",
      "The built in random generator can generally be trusted more than your own intuition about randomness." : "El construido en el generador aleatorio generalmente se puede confiar más que su propia intuición sobre la aleatoriedad.",
      "If cryptographic randomness isn t available in your browser, this page will show a warning and the generate button will not work." : "Si la aleatoriedad criptográfica no está disponible en su navegador, esta página mostrará una advertencia y el botón generar no funcionará.",
      "In that case you might choose to use your own source of entropy." : "En ese caso, puede optar por utilizar su propia fuente de entropía.",
      "You are not a good source of entropy." : "No eres una buena fuente de entropía.",
      "License" : "Licencia",
      "The software is provided 'as is', without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. In no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software." : "El software se proporciona \"tal cual\", sin garantía de ningún tipo, expresa o implícita, incluyendo pero no limitado a las garantías de comerciabilidad, aptitud para un propósito particular y no infracción. En ningún caso los autores o titulares de los derechos de autor serán responsables de ninguna reclamación, daños u otra responsabilidad, ya sea en una acción contractual, extracontractual o de otro tipo, que surja de, o en relación con el software o el uso u otros tratos en el software.",
      "Offline Usage" : "Uso sin conexión",
      "You can use this tool without having to be online." : "Puede utilizar esta herramienta sin tener que estar en línea.",
      "In your browser, select file save-as, and save this page as a file." : "En su navegador, seleccione archivo guardar como, y guarde esta página como un archivo.",
      "Double-click that file to open it in a browser on any offline computer." : "Haga doble clic en ese archivo para abrirlo en un navegador en un equipo sin conexión.",
      "Alternatively, download the file from the repository" : "También puede descargar el archivo desde el repositorio",
      "This project is 100% open-source code" : "Este proyecto es 100% de código abierto",
      "Get the source code from the repository" : "Obtener el código fuente desde el repositorio",
      "Libraries" : "Catálogo",
      "Click field to hide QR" : "Haga clic en el campo para ocultar QR",
      "Click field to show QR" : "Haga clic en el campo para mostrar QR",
      "Caution: Scanner may keep history" : "Precaución: El escáner puede guardar el historial",
      "<code>m/44'/0'/0'/0</code> generates public addresses": "<code>m/44'/0'/0'/0</code> genera direcciones públicas",
      "<code>m/44'/0'/0'/1</code> generates change addresses": "<code>m/44'/0'/0'/1</code> genera direcciones de cambio",
      "<code>m/44'/0'/0'</code> generates extended keys for import / export": "<code>m/44'/0'/0'</code> genera claves extendidas para importación / exportación",
      "<code>m/44'/0'/1'</code> for the next account. Continue incrementing for more accounts (most use a single account).": "<code>m/44'/0'/1'</code> para la siguiente cuenta. Continuar incrementando para más cuentas (la mayoría usa una sola cuenta).",
      "Accepts binary, base 6, 6-sided dice, base 10, hexadecimal, cards": "Acepta binario, base 6, dados de 6 lados, base 10, hexadecimal, tarjetas",
      "BIP32 Extended Key": "BIP32 Clave extendida",
      "BIP32 Extended Key (addresses only)": "BIP32 Clave extendida (sólo direcciones)",
      "Be careful - it can be easy to make mistakes if you don't know what you're doing.": "Tenga cuidado - puede ser fácil cometer errores si no sabe lo que está haciendo.",
      "Do <strong>NOT</strong> use phrases from books, lyrics from songs, your birthday or steet address, keyboard mashing, or anything you <i>think</i> is random, because chances are overwhelming it isn't random enough for the needs of this tool.": "<strong>NO UTILICE</strong> frases de libros, letras de canciones, su cumpleaños o dirección, golpe de teclado, o cualquier cosa que usted <i>pensar</i> es aleatorio, porque las posibilidades son abrumadoras no es lo suficientemente aleatorio para las necesidades de esta herramienta.",
      "Entropy values must be sourced from a <a href=\"https://en.wikipedia.org/wiki/Random_number_generation\" target=\"_blank\">strong source of randomness</a>.": "Entropy values must be sourced from a <a href=\"https://en.wikipedia.org/wiki/Random_number_generation\" target=\"_blank\">fuerte fuente de aleatoriedad</a>.",
      "For more info see the <a href=\"https:\/\/github.com\/bitcoin\/bips\/blob\/master\/bip-0049.mediawiki\" target=\"_blank\">BIP49 spec<\/a>." :"Para más información, consulte <a href=\"https:\/\/github.com\/bitcoin\/bips\/blob\/master\/bip-0049.mediawiki\" target=\"_blank\">BIP49 spec<\/a>.",
      "For more info see the <a href=\"http://www.mycelium.com/\" target=\"_blank\">Mycelium Wallet homepage</a>": "Para más información, consulte <a href=\"http://www.mycelium.com/\" target=\"_blank\">Mycelium Wallet homepage</a>",
      "For more info see the <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki\" target=\"_blank\">BIP39 spec</a>.": "Para más información, consulte <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki\" target=\"_blank\">BIP39 spec</a>.",
      "For more info see the <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki\" target=\"_blank\">BIP44 spec</a>.": "Para más información, consulte <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki\" target=\"_blank\">BIP44 spec</a>.",
      "For more info see the <a href=\"https://github.com/bitcoin/bitcoin/pull/8035\" target=\"_blank\">Bitcoin Core BIP32 implementation</a>": "Para más información, consulte <a href=\"https://github.com/bitcoin/bitcoin/pull/8035\" target=\"_blank\">Bitcoin Core BIP32 implementation</a>",
      "From entropy length (3 words per 32 bits)": "From entropy length (3 words per 32 bits)",
      "If cryptographic randomness isn't available in your browser, this page will show a warning and the generate button will not work.": "Si la aleatoriedad criptográfica no está disponible en su navegador, esta página mostrará una advertencia y el botón generar no funcionará.",
      "Mycelium Wallet": "Mycelium Wallet",
      "Only enter the <code>xpub</code> extended key into block explorer search fields, never the <code>xprv</code> key.": "Sólo ingrese el<code>xpub</code> la clave extendida en los campos de búsqueda del explorador de bloques, nunca <code>xprv</code> key.",
      "Read more at the <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki\" target=\"_blank\">official BIP32 spec</a>": "Leer más en <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki\" target=\"_blank\">official BIP32 spec</a>",
      "Read more at the <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki\">official BIP39 spec</a>": "Leer más en <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki\">official BIP39 spec</a>",
      "Read more at the <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki\" target=\"_blank\">official BIP44 spec</a>": "Leer más en <a href=\"https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki\" target=\"_blank\">official BIP44 spec</a>",
      "See the demo at <a href=\"http://bip32.org/\" target=\"_blank\">bip32.org</a>": "Ver la demostración en <a href=\"http://bip32.org/\" target=\"_blank\">bip32.org</a>",
      "Strength": "Strength",
      "The random mnemonic generator on this page uses a <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues\" target=\"_blank\">cryptographically secure random number generator</a>.": "El generador mnemónico aleatorio en esta página utiliza un <a href=\"https://developer.mozilla.org/en-US/docs/Web/API/RandomSource/getRandomValues\" target=\"_blank\">generador de números aleatorios criptográficamente seguro</a>.",
      "Use path <code>m/0'/0'</code> with hardened addresses.": "Use path <code>m/0'/0'</code> with hardened addresses.",
      "Use path <code>m/44'/0'/0'</code>.": "Use path <code>m/44'/0'/0'</code>.",
      "Use private keys at <a href=\"https://web.archive.org/web/20150707020924/https://brainwallet.org/\" target=\"_blank\">brainwallet.org</a>.": "Utilice las llaves privadas en <a href=\"https://web.archive.org/web/20150707020924/https://brainwallet.org/\" target=\"_blank\">brainwallet.org</a>.",
      "Word Count": "Word Count",
      "Based on estimates from zxcvbn using Filtered Entropy" : "Basado en estimaciones de zxcvbn utilizando la Entropía Filtrada",
      "Total bits of entropy may be less than indicated if any entropy event uses a weak source.":"Los bits totales de entropía pueden ser menores que los indicados si cualquier evento de entropía usa una fuente débil.",
      "Be careful - it can be easy to make mistakes if you don't know what you are doing.":"Tenga cuidado - puede ser fácil cometer errores si no sabe lo que está haciendo.",
      "Use path <code>m/0'/0</code>.":"Usar la ruta <code>m/0'/0</code>.",
      "<a href=\"https:\/\/en.wikipedia.org\/wiki\/Steganography#Physical\" target=\"_blank\">Steganography<\/a> may be beneficial when storing the mnemonic.": "<a href=\"https:\/\/en.wikipedia.org\/wiki\/Steganography#Physical\" target=\"_blank\">Esteganografía<\/a> puede ser beneficioso cuando se almacena el mnemotécnico.",
      "Please refer to <a href=\"https:\/\/github.com\/iancoleman\/bip39\/blob\/master\/LICENSE\" target=\"_blank\">the software license<\/a> for more detail.": "Por favor refiérase a <a href=\"https:\/\/github.com\/iancoleman\/bip39\/blob\/master\/LICENSE\" target=\"_blank\">la licencia de software<\/a> para más detalles.",

    }
  );

