WORDLISTS = typeof WORDLISTS == "undefined" ? {} : WORDLISTS;
WORDLISTS["portuguese_brazil"] = [
    "abacate", "abaixo", "abandono", "abencoar", "aberto", "abertura", "abobora", "abraco", "abril", "absorver",
    "abstrato", "absurdo", "abuso", "academia", "acampamento", "acao", "acesso", "acidente", "acido", "acima",
    "aco", "acolher", "acordado", "acordar", "acordo", "acreditar", "acrescentar", "acucar", "acusar", "acustico",
    "adaptar", "adiante", "adicionar", "adivinhar", "admitem", "adotivo", "adquirir", "adulto", "aerobico", "aeroporto",
    "afastar", "afetivo", "afetuoso", "afiado", "afinidade", "aflicao", "agachar", "agarrar", "agente", "agora",
    "agosto", "agua", "aguarde", "aguia", "ainda", "aipo", "aja", "ajustar", "alarme", "album", "alcancar", "alcance",
    "alcool", "aldeia", "aleatoria", "alegre", "alegria", "aleia", "alem", "alerta", "alfa", "algodao", "alguem",
    "alho", "alimentacao", "alistar", "alivio", "alma", "almoco", "almofada", "alteracao", "alterar", "alto", "altura",
    "aluguel", "aluna", "aluno", "alvo", "alvorecer", "amador", "amanha", "amar", "amarelo", "amargo", "ambito",
    "ameaca", "amendoim", "amigos", "amostra", "ampliar", "analista", "anao", "ancora", "andar", "anel", "angulo",
    "animal", "ano", "anoitecer", "ansiedade", "ansioso", "antena", "antes", "antigo", "antiguidade", "anual",
    "anunciar", "apagar", "aparar", "aparecer", "aperto", "aplaudir", "aplicar", "apoiar", "aposentar", "apreciar",
    "aprender", "aprovar", "apto", "ar", "aranha", "arcaico", "arco", "area", "areia", "arena", "argila", "argumentar",
    "argumento", "arma", "armadilha", "armado", "armadura", "armario", "arquivo", "arrepender", "arrepio", "arroz",
    "arte", "artefato", "artico", "artista", "artwork", "arvore", "asa", "asma", "asno", "aspecto", "aspero", "assado",
    "assalto", "assemelhar", "assento", "assumir", "ataque", "ate", "atinar", "atirar", "atitude", "atividade", "ativo",
    "atleta", "atomo", "ator", "atrai", "atras", "atraves", "atriz", "atual", "atualidade", "atualizacao", "atualizar",
    "atum", "auditar", "aumentar", "ausente", "auto", "autor", "autoria", "autorizar", "auxiliar", "avancar",
    "aventura", "avestruz", "aviso", "avistar", "azul", "baboseira", "bacharel", "bacon", "bagagem", "bairrista",
    "bala", "balanco", "baleia", "bambino", "bambu", "banana", "bancada", "banco", "bandeira", "bandeja", "bando",
    "banheiro", "barato", "barco", "barganha", "barra", "barraca", "barril", "barulho", "base", "basico", "batalha",
    "batata", "batedeira", "batedor", "batida", "bebe", "beber", "beijo", "beira", "beleza", "bem", "beneficiar",
    "berco", "biblioteca", "bicicleta", "bife", "bilhete", "biologia", "bitola", "blusa", "boa", "boba", "bobina",
    "bode", "bola", "bolha", "bolo", "bolsa", "bom", "bomba", "boneca", "bonita", "bonitinho", "bonus", "borda",
    "bordo", "borracha", "borrao", "braco", "bravo", "brecha", "breu", "breve", "brilhante", "brilho", "brinquedo",
    "brisa", "broca", "brocolis", "bronze", "bufalo", "bulbo", "buraco", "burro", "buscar", "cabeca", "cabelo", "caber",
    "cabine", "cabo", "cacar", "cacareco", "cacarejar", "cachorro", "cacto", "cadeira", "cafe", "cair", "caixa",
    "calmo", "caloroso", "camada", "camarada", "camarao", "cambalhota", "camera", "caminhao", "caminho", "campeao",
    "campo", "campones", "canal", "cancao", "cancelar", "canela", "caneta", "canguru", "canhao", "canoa", "cansado",
    "cantar", "caos", "capacete", "capacidade", "capaz", "capital", "capitao", "capitulo", "captura", "capturados",
    "capuz", "cara", "caracteristica", "carbono", "cardapio", "carga", "carimbo", "carne", "carpo", "carranca",
    "carregar", "carrinho", "carro", "carta", "cartao", "carvalho", "carvoeira", "casa", "casal", "casamento", "caso",
    "cassino", "casta", "castanha", "castanho", "castelo", "casual", "catalogo", "categoria", "causa", "cavalo",
    "caverna", "cebola", "cedo", "cego", "celere", "cem", "cena", "censo", "ceramica", "cerca", "cercar", "cerco",
    "cereal", "cerebro", "cereja", "cerne", "certo", "cervo", "cesta", "chama", "chamine", "chao", "chapeu", "charuto",
    "chateado", "chave", "chef", "chefe", "chegar", "chicote", "chifre", "chique", "choque", "chorar", "chuva", "ciclo",
    "cidadao", "cidade", "ciencia", "cimento", "cinto", "circulo", "citacao", "citar", "ciumes", "civil", "clemencia",
    "cliente", "clima", "clinica", "clique", "clube", "cobertor", "cobertura", "cobre", "cobrir", "coco", "codigo",
    "coelho", "cofre", "cogumelo", "coiote", "coisa", "cola", "coletar", "colheita", "colher", "colisao", "colocar",
    "colossal", "coluna", "combinar", "combustivel", "comecar", "comercio", "comicio", "comida", "companhia",
    "comparecer", "compartilhar", "componente", "comportamento", "compra", "comprador", "comprimento", "comprimido",
    "comum", "conceder", "concha", "concordar", "conduta", "conectados", "conectar", "confiar", "configuracao",
    "confirmar", "conforto", "congeladas", "congresso", "conhecer", "conjurar", "consciente", "conselho", "consentir",
    "consertar", "considerar", "construir", "conta", "contar", "contato", "contemplacao", "contente", "contratar",
    "controlar", "convencer", "conversa", "conversar", "convir", "convite", "copia", "copo", "cor", "coracao",
    "coragem", "coral", "corar", "corpo", "corre", "corredor", "correto", "corrida", "corrigir", "corroer", "cortina",
    "corvo", "costa", "costela", "cotovelo", "cozinha", "cozinhar", "cracha", "cranio", "cratera", "credito",
    "cremalheira", "creme", "crescer", "crianca", "criceto", "crime", "crise", "cristal", "critico", "cronica", "cru",
    "crucial", "cruel", "cruz", "cruzeiro", "cubo", "cuidado", "culpa", "cultura", "cume", "curioso", "curso", "curto",
    "curva", "custo", "custodia", "dados", "danca", "danificar", "dar", "debaixo", "debate", "decada", "decidir",
    "declinio", "decorar", "decretar", "dedicar", "dedo", "defesa", "definir", "delgado", "delicado", "demitir",
    "demolir", "demora", "dente", "dentista", "dentro", "depender", "depois", "deposito", "depressa", "deputado",
    "deriva", "derivar", "desafiar", "desagradavel", "desajeitado", "desaparecer", "descobrir", "desconhecido",
    "descrever", "desculpa", "desde", "desdobrar", "desejo", "desenhar", "desenvolver", "deserto", "desespero",
    "desfazer", "desfiladeiro", "desistir", "deslizar", "desmaio", "desnivelado", "desordem", "desperdicio",
    "destravar", "destruir", "desvaneca", "desvendar", "desviar", "detalhe", "detritos", "deusa", "dever", "devo",
    "dez", "dezembro", "dia", "diagrama", "diamante", "diario", "dica", "diesel", "dieta", "diferir", "dificil",
    "digital", "digitalizacao", "digitar", "dignidade", "dilema", "diminuir", "dinamico", "dinheiro", "dinossauro",
    "direto", "dirigir", "discar", "discordar", "disparo", "dispor", "dispositivo", "distancia", "distinto", "diversao",
    "diverso", "divertido", "dividido", "dividir", "divorcio", "dizer", "doador", "doar", "dobra", "doce", "documento",
    "doenca", "doente", "dois", "dominar", "dominio", "doninha", "dormir", "dose", "doze", "dragao", "drama",
    "drastico", "duna", "duplo", "durante", "duto", "eco", "ecologia", "economia", "editar", "educar", "efemero",
    "efetivo", "eixo", "elator", "elefante", "elegante", "elemento", "eles", "eletrico", "elevador", "elite",
    "embaralhar", "embarcacao", "embarcar", "emblema", "embreagem", "embrulho", "emergir", "emocao", "empenhar",
    "empinar", "empregada", "empregar", "empresa", "emprestado", "emprestar", "emprestimo", "empurrao", "empurrar",
    "encarnar", "encontrado", "encontrar", "endereco", "endossar", "energia", "enfadonho", "enfermeira", "enfermo",
    "engenho", "engolir", "engracado", "enigma", "enorme", "enriquecer", "ensaio", "enseada", "ensinar", "ensino",
    "ensolarado", "entornar", "entrada", "entrar", "entre", "entregar", "entulho", "entupir", "envelope", "enviar",
    "envolver", "enxame", "episodio", "equilibrar", "equipamento", "equipar", "equipe", "era", "erguido", "ermo",
    "erosao", "errado", "erro", "erupcao", "esboco", "escada", "escala", "escalada", "escambo", "escapar", "escape",
    "esclarecer", "escola", "escolha", "escolher", "escondido", "escorpiao", "escova", "escreva", "escrita",
    "escritorio", "escriturario", "escrivaninha", "escudo", "esfarelar", "esfera", "esforco", "esfregar", "esmagamento",
    "espacial", "espaco", "espada", "espalhar", "especial", "especiaria", "espelho", "esperanca", "esperar", "espero",
    "esperto", "espiao", "espigao", "espirito", "esporte", "esposa", "espuma", "esquadra", "esqueco", "esquema",
    "esquerda", "esqui", "esquilo", "esquisito", "essencia", "esta", "estacao", "estadio", "estado", "estalo",
    "estavel", "estereo", "estilo", "estimacao", "estojo", "estomago", "estoque", "estrada", "estragar", "estrangeiro",
    "estrategia", "etapa", "eterno", "etica", "etiqueta", "evidencia", "evidente", "evita", "evitar", "evocar",
    "evoluir", "exame", "exato", "excesso", "excitar", "excluir", "exclusivo", "executar", "exemplo", "exercicio",
    "exercito", "exibicao", "exigem", "exigir", "exilio", "existir", "exotico", "expandir", "expediente",
    "experimentar", "expirar", "explicar", "explosao", "expor", "exposicao", "exposto", "expressar", "extenso",
    "exterior", "externo", "extra", "faca", "facil", "facilmente", "faco", "faculdade", "fadiga", "falar", "falcao",
    "falecimento", "falha", "falso", "fama", "familia", "faminto", "famoso", "fantasia", "fantasma", "fardo",
    "farejar", "fatal", "fatia", "favor", "favorito", "fazenda", "fe", "febre", "fechar", "federal", "feijao",
    "feio", "feliz", "femea", "fenda", "feriado", "ferido", "ferramenta", "ferro", "ferver", "festa", "festival",
    "fevereiro", "fibra", "ficcao", "fiel", "figura", "filha", "filme", "filtro", "fim", "final", "fino", "fio",
    "fique", "fiscal", "fisico", "fita", "flash", "flecha", "flor", "floresta", "fluido", "flutuador", "flutuar",
    "foco", "fofoca", "fogao", "fogo", "foguete", "folha", "fonte", "fora", "forca", "fornalha", "fornecedor",
    "fornecem", "fornecer", "forno", "forte", "fortuna", "forum", "fosforo", "fossil", "foto", "fotografia", "fragil",
    "fragmento", "frango", "franja", "frase", "frente", "frequente", "frequentemente", "fresco", "frete", "fronteira",
    "frustrar", "fruta", "fugir", "fulgor", "fumaca", "funcionarios", "fundicao", "fundir", "furia", "futebol",
    "futuramente", "futuro", "gado", "gafe", "gaiola", "galaxia", "galeria", "galinha", "ganhar", "ganho", "ganso",
    "garagem", "garantia", "garantir", "garfo", "garoto", "garra", "garrucha", "gas", "gastar", "gatilho", "gatinho",
    "gato", "geada", "geleia", "gelo", "gemeo", "genero", "gengibre", "genio", "genuino", "geral", "gerir", "gesto",
    "gigante", "ginastica", "girafa", "girar", "giro", "giz", "globo", "gloria", "golfinho", "gordo", "gorila",
    "gospel", "gostar", "gosto", "gotejamento", "governo", "graca", "gracejo", "grade", "grama", "gramado", "grampo",
    "grande", "grao", "grau", "gravidade", "greve", "grilo", "grosseiro", "grunhido", "grupo", "guarda", "guardanapo",
    "guaxinim", "guerra", "guerreiro", "guia", "guindaste", "guri", "ha", "habilidade", "habilitar", "habitante",
    "habito", "hamburguer", "haste", "herdar", "heroi", "hibrido", "historia", "hoje", "holandes", "homem", "hoquei",
    "hora", "horrivel", "horror", "hospedeiro", "hospital", "hotel", "humano", "humilde", "humor", "icone", "idade",
    "ideia", "identificar", "ignorar", "igual", "iguaria", "ilegal", "ilha", "imagem", "imenso", "imitar", "impacto",
    "impor", "importam", "imprecisao", "impressao", "impressionante", "impulsionar", "impulso", "imune", "inalar",
    "inativo", "incapaz", "inclinar", "incluir", "incomum", "inconsciente", "incorporado", "indagacao", "indicar",
    "indice", "industria", "inexato", "infantil", "infeliz", "inferior", "infligir", "informar", "ingenuo", "inicial",
    "inicio", "inimigo", "injetar", "injusto", "inocente", "inquerito", "inquilino", "insano", "inscrever", "inseto",
    "insignia", "inspirar", "instalar", "instar", "intacto", "inteligente", "interesse", "interior", "interminavel",
    "interruptor", "inutil", "inverno", "investir", "invez", "irma", "irmao", "isolar", "item", "ja", "jaguar",
    "jamais", "janela", "jantar", "jaqueta", "jarda", "jardim", "jarra", "jazz", "jeans", "jeito", "joelho", "jogo",
    "joia", "jornada", "jovem", "juiz", "junior", "junte", "juntos", "jurar", "juventude", "kalanga", "ketchup",
    "kiwi", "la", "labaro", "labirinto", "laboratorio", "laco", "lacuna", "lado", "lagarto", "lago", "lagoa", "lagosta",
    "laje", "lamina", "lampada", "lancamento", "lancar", "lanche", "lapis", "laptop", "laranja", "largo", "largura",
    "lata", "latino", "lava", "lavanderia", "lavar", "lazer", "leao", "legal", "lei", "leilao", "leite", "lembrar",
    "lenda", "lente", "lento", "leopardo", "lerdo", "leste", "letra", "levantar", "leve", "liberdade", "licao",
    "licenca", "lider", "ligacao", "ligar", "ligeiro", "limao", "limitar", "limite", "limpar", "lingua", "linguica",
    "linha", "liquido", "lista", "lisura", "livre", "livro", "lixo", "lobo", "local", "localidade", "locomocao",
    "logica", "loja", "lona", "longe", "longo", "loteria", "louco", "louvor", "lua", "lucro", "lugar", "lunar", "luta",
    "lutar", "luva", "luxo", "maca", "macaco", "madeira", "madrugada", "mae", "magia", "magnetico", "maior", "mais",
    "mal", "malha", "maluco", "mamae", "mamifero", "mandato", "manga", "manha", "mansao", "manteiga", "manual", "mao",
    "maquina", "mar", "maravilha", "marca", "marcha", "mare", "marfim", "margem", "marido", "marinho", "marmore",
    "martelo", "mascara", "massa", "matematica", "material", "matriz", "maximo", "mazela", "mecanico", "medalha",
    "media", "medico", "medida", "meia", "meio", "mel", "melancolia", "melhor", "melhorar", "melodia", "membro",
    "memoria", "mencao", "menina", "menor", "mensagem", "mente", "mentiroso", "mercado", "mercearia", "mergulho",
    "merito", "mes", "mesa", "mesmo", "metade", "metal", "metodo", "metro", "midia", "milagre", "milhao", "milho",
    "minimo", "minusculo", "minuto", "mira", "miseria", "misericordia", "misterio", "mistura", "misturado", "misturar",
    "mito", "moda", "modelo", "moderno", "modificar", "moeda", "moita", "molhado", "molho", "momento", "monitor",
    "monstro", "montanha", "monte", "moral", "mosca", "mosquito", "mostra", "motor", "movel", "mover", "movimento",
    "mudanca", "muito", "mula", "mulher", "multidao", "multiplicar", "mundo", "musculo", "museu", "musica", "mutuo",
    "nacao", "naco", "nada", "nadar", "nanico", "nariz", "nascimento", "natureza", "navalha", "navio", "necessidade",
    "necessitar", "negacao", "negar", "negativo", "negligencia", "negocio", "nem", "nervo", "neutro", "neve", "nevoa",
    "ninho", "nivel", "nobre", "noite", "noivado", "nome", "nomeacao", "noodle", "normal", "norte", "nota", "notavel",
    "noticia", "novamente", "novela", "noz", "nuclear", "numero", "nunca", "nuvem", "obedecer", "objetivo", "objeto",
    "obrigado", "obrigar", "obscurecer", "observar", "obstaculo", "obtivermos", "obvio", "oceano", "oco", "ocorrencia",
    "ocorrer", "ocupado", "odor", "oeste", "oferta", "oficio", "oito", "ok", "ola", "oleo", "olho", "olimpico", "oliva",
    "ombro", "ombros", "omitir", "onda", "onde", "ondulacao", "onibus", "opcao", "opera", "opiniao", "opor", "orbita",
    "orcamento", "ordem", "ordenar", "orfao", "organizar", "orgao", "orgulho", "orgulhoso", "orientar", "original",
    "osso", "ostra", "ou", "ourico", "ouro", "ousado", "outono", "outro", "outrora", "outros", "outubro", "oval",
    "ovas", "ovo", "oxigenio", "ozonio", "pa", "paciente", "pacote", "pacto", "padrao", "padre", "pagamento", "pagina",
    "pai", "painel", "pais", "palacio", "palavra", "palestra", "palhaco", "palma", "palpavel", "panda", "panico",
    "pano", "pantano", "pantera", "pao", "papagaio", "papel", "par", "parada", "paragem", "parede", "parente",
    "parodiar", "parque", "parte", "partido", "partilhado", "passar", "passaro", "passatempo", "passeio", "passo",
    "patife", "patim", "pato", "patrao", "patrocinador", "patrulha", "pausa", "pavimentar", "paz", "pe", "peca",
    "pedra", "peito", "peixe", "pele", "pelicano", "pelicula", "pena", "penhasco", "penhor", "pensamento", "pequeno",
    "pera", "perdao", "perfeito", "perguntar", "pericia", "perigo", "permanecer", "permitir", "perna", "personalizadas",
    "perto", "peru", "pesado", "pescoco", "pesquisa", "pessoa", "pessoas", "piano", "picada", "piloto", "pimenta",
    "pioneiro", "pipa", "piquenique", "piramide", "piscadela", "piscina", "pista", "pistola", "pizza", "planeta",
    "plano", "planta", "plastico", "plugue", "po", "pobreza", "poder", "poeira", "poema", "poeta", "polar", "polegada",
    "polegar", "policia", "polo", "polpa", "pomar", "pomba", "pombo", "ponei", "pontape", "ponte", "ponto", "popular",
    "porco", "porque", "porrete", "porta", "portao", "porto", "posicao", "possivel", "postar", "poucos", "poupar",
    "prado", "praia", "prata", "pratica", "prato", "prazer", "prazo", "preco", "preferir", "preguicoso", "prejuizo",
    "premio", "prender", "preocupacao", "preparar", "presente", "pressa", "preto", "prever", "primario", "primavera",
    "primeiro", "primo", "primor", "principal", "principio", "prioridade", "prisao", "privado", "problema", "processo",
    "procurar", "produzir", "profundidade", "programa", "progredir", "projeto", "promover", "pronto", "propelir",
    "proposito", "propriedade", "proprietario", "proprio", "prosperar", "proteger", "prova", "provincia", "proximo",
    "publico", "pudim", "pulso", "pureza", "puxar", "quadrado", "quadril", "quadrinho", "quadro", "quais", "qualidade",
    "qualquer", "quando", "quantidade", "quarto", "quase", "que", "quebradico", "queijo", "queque", "quer", "questao",
    "questionario", "quota", "ra", "rabo", "radar", "radio", "raiva", "rampa", "rancho", "ranhura", "rapido", "raposa",
    "raro", "rascunho", "raso", "rastejar", "rastrear", "rato", "razao", "reabrir", "real", "rebanho", "rebelde",
    "receber", "receita", "receoso", "reciclar", "recompensa", "reconstruir", "recordacao", "recruta", "recurso",
    "recusar", "rede", "redor", "reduzir", "refletir", "reforma", "refrigerante", "regalo", "regiao", "regime",
    "regional", "registro", "regra", "regulado", "regular", "reino", "reivindicacao", "rejeitar", "relance",
    "relativamente", "relatorio", "relaxe", "relogio", "reluzente", "relva", "remendo", "remeter", "remover",
    "renda", "render", "renovar", "reparar", "repente", "repetir", "repolho", "resgatar", "resistir", "resolver",
    "responda", "resposta", "ressalto", "restante", "resto", "resultado", "resvalar", "retiro", "retorna", "reuniao",
    "reunir", "revelar", "revisao", "rico", "rifle", "rigido", "rim", "rio", "riqueza", "rir", "risadinha", "risco",
    "ritmo", "ritual", "rival", "robo", "robusto", "roda", "rodar", "romance", "romaria", "rosa", "rota", "rotulo",
    "rua", "rubor", "rubrica", "rural", "sabedoria", "sabonete", "sabor", "safra", "saia", "saida", "sair", "sal",
    "salada", "salao", "salario", "salmao", "saltar", "salvar", "sangue", "sapato", "satisfazer", "satoshi", "saudacao",
    "saude", "secao", "seco", "seculo", "seda", "segmento", "segredo", "segue", "segundo", "seguranca", "seguro",
    "seis", "sela", "selecionar", "selva", "selvagem", "semelhante", "semente", "seminario", "sempre", "senhora",
    "senhorita", "senior", "sensato", "sentido", "sentir", "sereia", "serie", "serpente", "servico", "sessao", "sete",
    "show", "significar", "silencioso", "silica", "simbolo", "simples", "sinal", "sino", "sintoma", "sistema", "situar",
    "slogan", "so", "sobrancelha", "sobre", "sobrinho", "social", "soco", "socorro", "sofa", "sofrer", "sol", "solar",
    "soldado", "soletrar", "solido", "solitario", "solta", "solucao", "som", "sombra", "sombrinha", "somente", "sonho",
    "sopa", "sorrir", "sorte", "sozinho", "spray", "suave", "substituir", "sucesso", "suco", "suficiente", "sufoco",
    "sugerir", "sugestao", "sujeira", "sujeito", "sul", "super", "superficie", "superior", "suporte", "supremo",
    "surpreendente", "surpresa", "suspeito", "suspiro", "sussurro", "sustentar", "susto", "tabaco", "tal", "talento",
    "tamanho", "tambem", "tambor", "tamborete", "tanque", "tapete", "tarde", "tarefa", "tarifa", "tartaruga",
    "tatuagem", "taxa", "taxi", "tecido", "tela", "telefone", "tema", "tempo", "tendencia", "tenis", "tentativas",
    "teoria", "ter", "terminar", "terno", "terra", "tesouras", "teste", "testemunha", "testemunho", "teto", "texto",
    "tia", "tigre", "tijolo", "timido", "tio", "tipica", "tipo", "titulo", "tocha", "todo", "todos", "tom", "tomate",
    "tombar", "tonto", "topo", "toque", "torcao", "tornado", "tornozelo", "torrada", "torre", "torrente", "total",
    "totalidade", "trabalho", "traco", "trafego", "tragico", "trair", "trama", "tramela", "trancar", "transferir",
    "transportar", "tratar", "trazer", "treinador", "trem", "tres", "triangulo", "tribo", "trigo", "trilho",
    "trimestre", "triplo", "triste", "tristeza", "triunfar", "troca", "trofeu", "trombada", "trombeta", "tropecar",
    "trovao", "truque", "tubo", "tumulto", "tunel", "turista", "um", "umido", "unico", "unidade", "uniforme",
    "universo", "urbano", "urdidura", "usar", "usava", "uso", "usual", "util", "utilidade", "uva", "vacuo", "vagao",
    "vago", "vale", "valido", "valise", "valor", "valvula", "van", "vapor", "vara", "varanda", "varios", "vassoura",
    "vazio", "veiculo", "vela", "velho", "velocidade", "veludo", "vencedora", "vender", "ventilador", "verao", "verbo",
    "verdade", "verdadeiramente", "verdadeiro", "verde", "vereda", "verifica", "verificar", "versao", "verter", "vespa",
    "vestem", "vestido", "vestigio", "vestir", "vestuario", "veterano", "vez", "viagem", "viavel", "vibrante",
    "viciado", "vicioso", "vida", "video", "vidro", "vincular", "vinho", "vintage", "vinte", "violao", "violino",
    "vir", "virtual", "virus", "visa", "visao", "visita", "vislumbre", "vista", "visual", "vital", "vitoria", "viver",
    "vivido", "vivo", "voar", "vocal", "voce", "volta", "volume", "vontade", "voto", "voz", "vulcao", "xarope",
    "xerife", "zangado", "zebra", "zero", "zona", "zoologico", "zumbido"
];
